[package]
name = "PDFrust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
lopdf = "0.36"
inquire = "0.7.5"
derive_more = { version = "2", features = ["from", "display"] }

